create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  player_id text not null check (char_length(player_id) between 3 and 120),
  game_id text not null check (game_id in ('adventure', 'cipher', 'reflex')),
  score integer not null default 0 check (score between 0 and 99999),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists game_scores_player_game_idx on public.game_scores (player_id, game_id, created_at desc);

alter table public.game_scores enable row level security;

revoke all on public.game_scores from anon, authenticated;
grant insert on public.game_scores to service_role;

comment on table public.game_scores is 'نتائج ألعاب منصة BMO، تُكتب عبر دالة الخادم فقط.';
